# Generated by Django 5.0.6 on 2026-03-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_access', models.CharField(choices=[('none', 'None'), ('read', 'Read Only'), ('read_write', 'Read & Write')], default='read', max_length=10)),
                ('authenticated_access', models.CharField(choices=[('none', 'None'), ('read', 'Read Only'), ('read_write', 'Read & Write')], default='read', max_length=10)),
                ('team_access', models.CharField(choices=[('none', 'None'), ('read', 'Read Only'), ('read_write', 'Read & Write')], default='read_write', max_length=10)),
                ('owner_access', models.CharField(choices=[('none', 'None'), ('read', 'Read Only'), ('read_write', 'Read & Write')], default='read_write', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
